import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Sidebar para Tutoriais - reconhece automaticamente as categorias
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  // Você pode também criar uma sidebar mais estruturada se preferir:
  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Categorias',
  //     items: [
  //       {
  //         type: 'autogenerated',
  //         dirName: '.',
  //       },
  //     ],
  //   },
  // ],
};

export default sidebars;