import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutoriais: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],

  'api-referencias': [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
