/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutoriais',
      items: [{ type: 'autogenerated', dirName: 'tutoriais' }],
    },
    {
      type: 'category',
      label: 'API Referências',
      items: [{ type: 'autogenerated', dirName: 'api-referencias' }],
    },
  ],
};

module.exports = sidebars;